version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-build
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-build
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000/api

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "3000:3000"